version: '2'
services: 

  web:
      build: .
      container_name: predictsite
      volumes: 
      - .:/code
      expose: 
        - 8080
      command: bash -c "gunicorn --workers=3 policy_renew_predict_site.wsgi -b 0.0.0.0:8080"

  nginx:
      restart: always
      build: ./nginx/
      volumes: 
        - ./nginx/:/etc/nginx/conf.d
        - ./logs/:/code/logs
      ports: 
        - "1221:80"
      links:
        - web  

